---
title: "Statistical Inference Project Part 1"
author: "Ryan Wissman" (speedy3d)
date: "Saturday, January 24, 2015"
output: pdf_document
---

#Coursera Statistical Inference Course Project

This project consists of two parts:

1) Data simulations
2) Data Analysis

More information regarding this project:

In this project you will investigate the exponential distribution in R and compare it with the Central Limit Theorem. The exponential distribution can be simulated in R with rexp(n, lambda) where lambda is the rate parameter. The mean of exponential distribution is 1/lambda and the standard deviation is also 1/lambda. Set lambda = 0.2 for all of the simulations. You will investigate the distribution of averages of 40 exponentials. Note that you will need to do a thousand simulations.

This project will cover 3 areas:

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials.  You should
1. Show the sample mean and compare it to the theoretical mean of the distribution.
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
3. Show that the distribution is approximately normal.


##Part 1: Simulation

First we will need to run a simulation of 

```{r}
#set the number of simulations
n_sim <- 1000

#set the sample size
n_samples <- 40

#set the random seed
set.seed(1313)

#set the value of lambda
lambda <- 0.2

```
